version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ignite-node
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  app:
    build: .
    container_name: ignite-node
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite

volumes:
  pgdata:
    driver: local
